---
CSR1:
  hostname: "csr1.njrusmc.net"
  groups:
    - "ios"
  data:
    node_id: 101
    ipsla_addr: "10.0.0.101"

CSR2:
  hostname: "csr2.njrusmc.net"
  groups:
    - "ios"
  data:
    node_id: 102
    ipsla_addr: "10.0.0.102"
...
